baseurl: https://jaigansa.netlify.app/
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: JAIGANSA

languages:
    en:
        languageName: English
        title: JAIGANSA
        weight: 1
    ta:
        languageName: Tamil
        title: ஜெய்கன்சா
        weight: 2
    tan:
        languageName: Tanglish
        languagedirection: Jaigansa
        title: jaigansa
        weight: 3
